version: '3.8'
services:
  infinity:
    image: michaelf34/infinity:0.0.23
    command: --model-name-or-path sentence-transformers/paraphrase-multilingual-mpnet-base-v2 --port 8080
    ports:
      - "8089:8080"
    tty: true # Equivalent to '-it' in Docker CLI, ensures the container's stdin is kept open
    restart: always # Optional, ensures the container restarts if it crashes or on system reboot    